services:
  - type: web
    name: backend
    env: docker 
    dockerfilePath: ./backend/Dockerfile
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false 
      - key: JWT_SECRET
        value: unSecretoMuySegurO123! # <<< ¡IMPORTANTE! REEMPLAZA CON UNA CLAVE SEGURA Y REAL
      - key: PORT
        value: "10000" 

  - type: web
    name: frontend
    env: docker 
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: npm install && npm run build
    plan: free
    envVars:
      - key: VITE_BACKEND_URL
        value: http://backend:10000