services:
  - type: web
    name: backend
    env: docker
    plan: free
    build:
      context: ./backend
      dockerfilePath: Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false 
      - key: JWT_SECRET
        value: unSecretoMuySegurO123!
      - key: PORT
        value: "10000"

  - type: web
    name: frontend
    env: docker
    plan: free
    build:
      context: ./frontend
      dockerfilePath: Dockerfile
    envVars:
      - key: VITE_BACKEND_URL
        value: http://backend:10000
