services:
  - name: backend
    type: web
    env: docker
    plan: free
    # 👇 Aquí especificas carpeta + Dockerfile
    build:
      context: ./backend
      dockerfilePath: Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        value: unSecretoMuySegurO123!
      - key: PORT
        value: "10000"

  - name: frontend
    type: web
    env: docker
    plan: free
    build:
      context: .
      dockerfilePath: frontend/Dockerfile
    envVars:
      - key: VITE_BACKEND_URL
        value: http://backend:10000
