# render.yaml - Pega este contenido completo en tu archivo.

services:
  - type: web
    name: backend
    env: node
    dockerfilePath: ./backend/Dockerfile
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    plan: free
    ports:
      - 3000 # Puerto que tu backend Node.js expone internamente
    envVars:
      - key: MONGODB_URI # Variable de entorno para MongoDB
        sync: false # Su valor se definirá en la interfaz de Render.
      - key: JWT_SECRET
        value: unSecretoMuySegurO123! # <<< REEMPLAZA CON TU CLAVE REAL
      - key: PORT
        value: "3000"

  - type: web
    name: frontend
    env: static # Render servirá los archivos estáticos generados
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: npm install && npm run build
    staticPublishPath: ./frontend/dist # Carpeta donde Vite/React pone los archivos construidos
    plan: free
    envVars:
      # URL del backend para que el frontend la conozca.
      # 'backend' aquí se refiere al nombre de tu otro servicio en Render.
      - key: VITE_BACKEND_URL
        value: http://backend:3000